= F# TDMS Support image:https://ci.appveyor.com/api/projects/status/neahoo6surfs4bo6?svg=true[link=https://ci.appveyor.com/project/mettekou/fsharp-data-tdms] image:https://buildstats.info/nuget/FSharp.Data.Tdms[link=https://www.nuget.org/packages/FSharp.Data.Tdms]

`FSharp.Data.Tdms` provides support for TDMS files[[the-ni-tdms-file-format]]<<#the-ni-tdms-file-format-entry,^[1]^>>. It allows a user to access these in a type-safe manner through a generative type provider, but also through plain old functions.

== License

`FSharp.Data.Tdms` is licensed under an MIT License. Please refer to https://github.com/mettekou/FSharp.Data.Tdms/blob/master/LICENSE[`LICENSE`] for its full text.

== Usage

=== From F#

Using the generative type provider, given a TDMS file `Experiment.tdms` with a channel containing floating-point values named `Channel1` within a group named `Group1`:

[source,fsharp]
----
open FSharp.Data

[<Literal>]
let Path = "Experiment.tdms"

type Experiment = TdmsProvider<Path>

let experiment = Experiment(Path)

experiment.Group1.Channel1.Data |> Array.iter (printfn "%f")
----

Alternatively, use the functions in the `FSharp.Data.Tdms` namespace, mainly those in the `File` module:

[source,fsharp]
----
open FSharp.Data.Tdms

File.read "Experiment.tdms" |>
    File.tryRawData<float> "Group1" "Channel1" |>
    Option.defaultValue [||] |>
    Array.iter (printfn "%f")
----

=== From C#

When using `FSharp.Data.Tdms` from C#, prefer the API for idiomatic C#:

[source,csharp]
----
using System;
using FSharp.Data.Tdms;

class Program
{
    static void Main(string[] args)
    {
        File.Read("Experiment.tdms").TryGetRawData("Group1", "Channel1", out double[] data);

        foreach (double sample in data)
        {
            Console.WriteLine(sample);
        }
    }
}
----

== References

[[the-ni-tdms-file-format-entry]]<<#the-ni-tdms-file-format,^[1]^>> National Instruments. 2019. The NI TDMS File Format. (January 2019). Retrieved January 12, 2019 from `http://www.ni.com/white-paper/3727/en/`.
